### ISSUE TITLE
Support for Statamic 3.4

### ISSUE THREAD

**Issue by MtDalPizzol** [statamic/eloquent-driver#113]
Hi folks! Just wondering if support for Statamic 3.4 will take long or is it just turning the corner?

**Comment by ryanmitchell** [comment]
I haven't come across anything that doesn't work in 3.4 but its always worth upgrading in a test/staging environment to iron out any pitfalls.

If you run into anything open issues with the specific errors so they can be looked into.

**Comment by jasonvarga** [comment]
There should really be anything needed apart from adjusting the composer constraint. Updating this package is on my todo list.

**Comment by MtDalPizzol** [comment]
@jasonvarga You're probably right. When I tried to upgrade Statamic, composer stopped me because the eloquent-driver had the older version as a dependency.
