### ISSUE TITLE
Live Preview Error

### ISSUE THREAD

**Issue by crackAT** [statamic/eloquent-driver#12]
Hi, 

when i use the live preview on a new entry and the entry is not saved, i get the following error. 

Trying to get property 'origin' of non-object

![Bildschirmfoto 2021-01-27 um 17 37 12](https://user-images.githubusercontent.com/6299060/106022636-58878680-60c6-11eb-87a7-c03bf6d079ba.png)

**Comment by mobunti** [comment]
@crackAT did you solve this? I had this last week and just reverted back to file mode because I couldn't see a solution but would like to get running in database mode. Got a customer who might need 30,000 entries and figured that was probably going to be more than file mode could handle

**Comment by crackAT** [comment]
Hei, no, didn't solve this. I told all CMS Users to use the live preview after saving the entry.

**Comment by ryanmitchell** [comment]
Can you check this against v1? I think this issue can be closed.
