### ISSUE TITLE
EntrySaving called after the model has been saved.

### ISSUE THREAD

**Issue by addgod** [statamic/eloquent-driver#120]
The EntrySaving event is called after the entry has been persisted to the database.

So if you in your listener, try to retrieve the original Entry, it will be the new entry, not the old one.

This is what I see

```
use Statamic\Events\EntrySaving;
use Statamic\Facades\Blink;
use Statamic\Facades\Entry;

class EntrySavingListener
{
    public function handle(EntrySaving $event)
    {
        if ($event->entry->id()) {
            $entry = Entry::find($event->entry->id()); <-- the new entry, not the old
            $original = $entry->model()->getOriginal(); <-- this would be the original, but this does not work with file driven install.
            Blink::put('old::' . $event->entry->id(), $original->toArray());
        }
    }
}
```

Can anyone else confirm this?

**Comment by ryanmitchell** [comment]
I think you're hitting up against the blink cache we're using to try and limit the number database queries.
If you `Blink::forget("eloquent-entry-{$entry->id()}"` you should get the old entry.

**Comment by addgod** [comment]
But the blink cache should not have been set at this time either should it?

**Comment by ryanmitchell** [comment]
If i `dd()` inside your listener (using the same code you provided), then the data is not saved to the database. Once I remove the dd then it works as expected.

Maybe you could take some time and make a sample repository showing your issue so it can be replicated and investigated?
