### ISSUE TITLE
Performance issues with blueprint as JSON field

### ISSUE THREAD

**Issue by ryanmitchell** [statamic/eloquent-driver#126]
@ryanmitchell @jasonvarga we're facing rather big performance issues with `blueprint` being stored in json instead of its own field, so I just wanted to hear you out if you're okay with pulling `blueprint` out of json with an index so queries don't take 5+ seconds to complete?

_Originally posted by @FrittenKeeZ in https://github.com/statamic/eloquent-driver/issues/114#issuecomment-1420531869_

**Comment by ryanmitchell** [comment]
I assume you're talking about queries you're writing rather than ones this driver is making?

if so, what about making it a `storedAs` column in your own migration - that allows you to query it independently but it's still using the JSON field field so the driver's code doesn't need to change.

**Comment by FrittenKeeZ** [comment]
It's also when using  `entries` fieldtype for relationships with the `blueprint` filter.
Another issue is trying to query entries for a specific site with a certain blueprint - right now you're forced to fetch the original, loop through them to get the localized entry, and filter whether they're published or not, which is rather cumbersome.

**Comment by ryanmitchell** [comment]
The localised entries issue should be solved by the [data propagation PR which is open at the moment](https://github.com/statamic/eloquent-driver/pull/114).
