### ISSUE TITLE
Possibility to override Asset class like possible with Entries via config file

### ISSUE THREAD

**Issue by lukeptchr** [statamic/eloquent-driver#131]
I came to a situation where I need to override the `shallowAugmentedArrayKeys` of the Asset. But there is no possibility to override the Asset class.

This is possible for Entries in `eloquent-driver.php` config file -> `entries.entry`.

So I suggest to add `assets.asset` in `eloquent-driver.php` .

And then change `Statamic\Eloquent\Assets\AssetRepository` 
from `AssetContract::class => Asset::class,`

To `AssetContract::class => config('statamic.eloquent-driver.assets.asset'),`

**Comment by ryanmitchell** [comment]
You can bind your own Asset class to the contract in your service provider, but yes that could definitely be made simpler with a config.

You could PR the config, then bind it like we do for entries:
https://github.com/statamic/eloquent-driver/blob/master/src/ServiceProvider.php#L181-L183

Then use that bound value in the AssetRepository.

**Comment by lukeptchr** [comment]
Yes I have the PR already ready locally. But this will be a breaking change since this will require the config file change.

**Comment by ryanmitchell** [comment]
It wouldnt be a breaking change if you specify the current default when using config() ?

**Comment by ryanmitchell** [comment]
Are you still planning on opening a PR for this @lukeptchr ?

**Comment by ryanmitchell** [comment]
I've opened a PR for this [over here](https://github.com/statamic/eloquent-driver/pull/171)

**Comment by lukevmk** [comment]
I'm sorry, I just saw this. Thanks for opening the PR!
