### ISSUE TITLE
Join collection entries doesn't seem to work

### ISSUE THREAD

**Issue by maxi032** [statamic/eloquent-driver#132]
I am trying to join table entries with itself based on a few criterias.
This is the query:

``` 
$query = EntryFacade::query()->leftJoin('entries as eTags', fn ($join) => $join
                ->whereColumn('eTags.id', 'entries.origin_id')
            )->select('entries.*','eTags.data as origin_data')
                ->where('entries.collection', 'news')
                ->where('entries.published', true)
                ->where('entries.origin_id', null)
                ->where('entries.site', $locale)
                ->limit($limit)->offset($offset);
        $entries = $query->get();
```

        I get 10 items as I have $limit set to 10 but the problem is that all the properties of those items are null.

![](https://user-images.githubusercontent.com/1525885/224061999-c48b2612-cdd4-4522-a8ef-037e45971cff.jpg)

If I run the query in a mysql client, I get the expected result.

This is the query:
<pre>
 "query" => "select * from `entries` left join `entries` as `eTags` on `eTags`.`id` = `entries`.`origin_id` where `entries`.`collection` = ? and `entries`.`published` = ? and `entries`.`origin_id` is null and `entries`.`site` = ? limit 10 offset 0 ◀"
    "bindings" => array:3 [▼
      0 => "news"
      1 => true
      2 => "en"
    ]
    "time" => 1.15
    </pre>
    
    I am using:

Environment
- Application Name: statamic
- Laravel Version: 9.51.0
- PHP Version: 8.2.3
- Composer Version: 2.5.4
- Environment: testing
- Debug Mode: ENABLED
- URL: statamic.test
- Maintenance Mode: OFF

Cache
- Config: NOT CACHED
- Events: NOT CACHED
- Routes: NOT CACHED
- Views: CACHED

Drivers
- Broadcasting: log
- Cache: statamic
- Database: mysql
- Logs: stack / daily
- Mail: smtp
- Queue: sync
- Session: file

Statamic
- Addons: 3
- Antlers: runtime
- Stache Watcher: Disabled
- Static Caching: Disabled
- Version: 3.4.3 PRO

Statamic Addons
- spatie/statamic-responsive-images: 2.15.2
- statamic/eloquent-driver: 1.2.0
- withcandour/aardvark-seo: 2.0.30

**Comment by ryanmitchell** [comment]
Are you trying to get the origin data for any entry? If so this PR should resolve that: https://github.com/statamic/eloquent-driver/pull/114
