### ISSUE TITLE
Filtering entries in the stack selector is case sensitive

### ISSUE THREAD

**Issue by robdekort** [statamic/eloquent-driver#137]
As opposed to the flat file driver, filtering entries in the stack selector is case sensitive. It should be case insensitive imo. 

1. Add an entries field with a stack selector
2. Open the stack selector
3. Search for entry like 'home'. It won't work. You need to type 'Home'. 

I've only noticed it for entries only as this is the only repository I use the Eloquent driver for.

**Comment by ryanmitchell** [comment]
I think this depends on the collation of your database (case insensitive or not). Do you know what yours is?

**Comment by robdekort** [comment]
Nope :-). But nice pointer. I'll get back to this tonight. Curious!

**Comment by ryanmitchell** [comment]
Hopefully I’m right - from memory it’s that! If your collection has _ci in it it’s case insensitive which would mean I’m wrong!

**Comment by ryanmitchell** [comment]
So it seems when the data is in a JSON field MySQL carries out case sensitive comparisons as the data comes back in binary. The solution seem to be either to make column and value lowercase, or to cast the json_unquoted value as CHAR. Both of these feel like we would have to add mysql specific code to the base eloquent query builder.

**Comment by robdekort** [comment]
I totally believe you 🤯😉

**Comment by ryanmitchell** [comment]
Another option would be to create a migration for your app that creates a generated column for title, and then MySQL will defer to using that in any queries:

```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('entries', function (Blueprint $table) {
            $table->string('title')->storedAs('JSON_UNQUOTE(data->>"$.title")');
        });
    }
};
```

**Comment by robdekort** [comment]
Wonderful! Thanks Ryan ❤️.
