### ISSUE TITLE
Preferences not saved in DB

### ISSUE THREAD

**Issue by espenlg** [statamic/eloquent-driver#141]
When changing the default settings and re-order the navigation it is stored in resources/preferences.yaml.

Maybe it is supposed to be this way? I can't decide.

**Comment by espenlg** [comment]
Same thing with Preferences > Preferences changes.

**Comment by ryanmitchell** [comment]
As these are user related my personal feeling is they should be handled by the eloquent users in core.

**Comment by espenlg** [comment]
I agree om the user settings, but what about the default settings 😆

**Comment by espenlg** [comment]
I did notice something strange though. I re-ordered the children in Collections, and moved Globals to the top. By default. Works fine in my local dev environment, but when I deployed to the live site Globals had moved, but the children of Globals / Collections did not change. Could it be related to the Eloquent Driver?

**Comment by espenlg** [comment]
![Screenshot 2023-04-02 at 19 25 35](https://user-images.githubusercontent.com/1135679/229368921-257a5537-0a46-46da-98af-dfa474e5acce.png)
![Screenshot 2023-04-02 at 19 26 05](https://user-images.githubusercontent.com/1135679/229368922-803add79-6d3a-4f53-863e-5cbac804bfde.png)

Screenshot of preferences.yaml containing the default settings, and screenshot of the result. I know the language is not the same, but the collections handles are the same.

**Comment by ryanmitchell** [comment]
Yeah I suppose we could add a config option to store the default preferences in eloquent, it's a bit niche and Im not sure a lot of people would use it. It would just be a case of extending Statamic\Preferences\DefaultPreferences and changing the save/__construct methods.

Want to work on it @espenlg ?

**Comment by espenlg** [comment]
@ryanmitchell Sounds scary to say the least 😬 But I may give it a shot 👍

**Comment by duncanmcclean** [comment]
Like @ryanmitchell said, storing preferences in the database is probably a bit niche, I don't know how many developers would actually want to do that.

However, if you want to do it, it's fairly easy to do yourself. I've whipped up [a Gist](https://gist.github.com/duncanmcclean/7387e8e69bbc441d66902a17350f693a#file-readme-md) which gives you everything you need to store default preferences in the DB instead.
