### ISSUE TITLE
Selecting a preset in Assets Container is not stored

### ISSUE THREAD

**Issue by espenlg** [statamic/eloquent-driver#143]
If I define a image manipulation preset, and then edit the container to select this preset it is not saved after clicking Save. When clicking Save the browser asks if I want to leave the page, and when it reloads the preset is not selected/saved.

Not 100% sure it is related to Eloquent Driver, but I've not had this problem on other sites.

**Comment by henze-housepedia** [comment]
I am facing the same issue. I see this is been two weeks now. Will it be merged?

**Comment by ryanmitchell** [comment]
This is available now in v2.1.0
