### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by geertjanknapen1** [statamic/eloquent-driver#146]
Heya, 

What's the licensing for this repo like?
Can I propose a MIT License?

I'd really like some parts of the project but, for how my company is using this, I would like to change some thing around that would not work properly for everyone, but I just want to make sure everyone is okay with it.

**Comment by ryanmitchell** [comment]
Best to email Statamic support for licensing enquiries.

**Comment by ryanmitchell** [comment]
I would contact support to be sure. On 17 Apr 2023, at 07:20, Geert-Jan Knapen ***@***.***> wrote:﻿

Best to email Statamic support for licensing enquiries.

Statamic CMS repo has a (slightly modified) MIT License, can I, therefore, assume this repo also falls under the same license or is contacting support still necessary ?
