### ISSUE TITLE
Separating the orderable tree from the collections

### ISSUE THREAD

**Issue by mkael1** [statamic/eloquent-driver#147]
In my use case I would like to be able to store the order of my entries in my database without having the store the collections themselves in my database. Is there any workaround to do this / a future release that allows this?

**Comment by ryanmitchell** [comment]
You can already specify which 'repositories' to store - entries can be db-driven and collections flat-file driven. See the config file for the options available.

**Comment by mkael1** [comment]
To be more precise I would like to be able to have my collections driver as file while having my collection entries tree/ tree_model (for the orderable entries) in my database
![image](https://user-images.githubusercontent.com/92281368/234084055-1fc482ff-9fbb-4f5a-ab51-de3d0e73da14.png)

**Comment by ryanmitchell** [comment]
There is an open PR for this: https://github.com/statamic/eloquent-driver/pull/133
