### ISSUE TITLE
Unable to sort on computed fields

### ISSUE THREAD

**Issue by robdekort** [statamic/eloquent-driver#149]
When you have computed fields you can't sort listing tables on them. The fields are calculated at run time and not stored in the database. Therefore isn't available for the database to sort on. 

I use this

```php
Collection::computed('applications', 'outing_title', function ($entry) {
    return optional($entry->outing)->title;
});
```

To make sure I can properly sort on an entries field, but alas.

**Comment by ryanmitchell** [comment]
We should store the computed field values in the database too. I'll work on that.

**Comment by robdekort** [comment]
You are awesome!

**Comment by jackmcdade** [comment]
He sure is! <3

**Comment by AntonCooper** [comment]
Would storing these values not become problematic? I've got many implementations of computed fields which require a dynamic values - I thought that was the whole purpose of computed fields, that they're have the ability to be evaluated at runtime?

**Comment by ryanmitchell** [comment]
The values would be stored so the value at the point of last save could be queried (sorting etc), but when retrieved from the data would be overwritten with your dynamic values. It *should* cover both use cases.
