### ISSUE TITLE
Return values from columns before data field

### ISSUE THREAD

**Issue by Lampone** [statamic/eloquent-driver#15]
I tried to use a sitemap addon (https://github.com/pecotamic/sitemap) and `updated_at` was always giving errors. 

EntryModel will always get values from the data-column before any other column. I think this should be changed to be the other way around -> First read column values then values from the data-column.

The following code is the issue:
https://github.com/statamic/eloquent-driver/blob/84b0d40c56c23be35ee0abd63db6a59e172dcf8b/src/Entries/EntryModel.php#L27

After I changed the code it worked: 
`
return parent::getAttribute($key) ?? Arr::get($this->getAttributeValue('data'), $key);
`

I think it would also be a good idea to filter out values from `data` if column for that value exists. Currently ` updated_at` exist as column and gets saved in `data`

**Comment by jesseleite** [comment]
Fixed in https://github.com/statamic/eloquent-driver/pull/29 👍
