### ISSUE TITLE
Every collection is fetched regardless of what collection I query

### ISSUE THREAD

**Issue by geertjanknapen1** [statamic/eloquent-driver#151]
I have a piece of code that gets me a certain collection entry, it looks as follows:

```php
public function getCollectionEntry(Page|string $slug, Collection|array $collection, ?Locale $locale = null): ?EloquentEntry
    {
        $locale = getLocaleEnum($locale);
        $slugValue = is_string($slug) ? $slug : $slug->value;
        $collections = is_array($collection) ? collect($collection)->pluck('value')->toArray() : [$collection->value];

        $cacheTags = $this->prepareCacheTags($collection);

        return Cache::tags($cacheTags)->remember(
            "get_collection_entry:{$locale->value}:$slugValue" . implode('-', $collections),
            config('custom.caching.ttl'),
            function () use ($slugValue, $locale, $collections) {
                /** @var EntryQueryBuilder $entryQueryBuilder */
                $entryQueryBuilder = EntryFacade::query();

                $entry = $entryQueryBuilder
                    ->whereIn('collection', $collections)
                    ->where('slug', $slugValue)
                    ->where('published', true)
                    ->first();

                // get entry in given target locale (defaults to current locale)
                return !is_null($entry) ? $entry->in($locale->value) : null;
            }
        );
    }
```

This piece of code is ran the moment I hit the `/en/servicedesk` url.
`$collections` in this case can be either an Enum with a single value, or an array. In this example I've already made sure that it's a single string, namely `dynamic_pages`.

However when I check the performance for this in the Laravel debug bar, I see that there are `SELECT * FROM entries WHERE collection = ... ;` for almost all my collections. 
Furthermore there are a lot of duplicate queries that seem to try to get the origin of a specific entry (that I am not even querying).

I am going to share examples below, what I wanna know though it, why is this happening? Am I doing something wrong?

### The query it does correctly;
<img width="908" alt="image" src="https://github.com/statamic/eloquent-driver/assets/33750300/9463f2ce-4491-4b69-8ad0-eab79f85e7cd">

### The unnecessary (I think) queries;
<img width="900" alt="image" src="https://github.com/statamic/eloquent-driver/assets/33750300/151d46a2-4cc5-42e5-a34f-76d26f656d22">

### A lot of duplicates;
<img width="901" alt="image" src="https://github.com/statamic/eloquent-driver/assets/33750300/fcf31ff4-7d0d-46ff-9cf3-0421a44cc528">

<img width="318" alt="image" src="https://github.com/statamic/eloquent-driver/assets/33750300/c813e7a8-f6ea-4345-ac69-780e541136f0">

### Coming from
![image](https://github.com/statamic/eloquent-driver/assets/33750300/42ea16b1-d50c-4a97-909e-bda16770d3da)

**Comment by ryanmitchell** [comment]
There are open PRs to resolve both of these. On 10 May 2023, at 15:26, Geert-Jan Knapen ***@***.***> wrote:﻿
I have a piece of code that gets me a certain collection entry, it looks as follows:
public function getCollectionEntry(Page|string $slug, Collection|array $collection, ?Locale $locale = null): ?EloquentEntry
    {
        $locale = getLocaleEnum($locale);
        $slugValue = is_string($slug) ? $slug : $slug->value;
        $collections = is_array($collection) ? collect($collection)->pluck('value')->toArray() : [$collection->value];

        $cacheTags = $this->prepareCacheTags($collection);

        return Cache::tags($cacheTags)->remember(
            "get_collection_entry:{$locale->value}:$slugValue" . implode('-', $collections),
            config('custom.caching.ttl'),
            function () use ($slugValue, $locale, $collections) {
                /** @var EntryQueryBuilder $entryQueryBuilder */
                $entryQueryBuilder = EntryFacade::query();

                $entry = $entryQueryBuilder
                    ->whereIn('collection', $collections)
                    ->where('slug', $slugValue)
                    ->where('published', true)
                    ->first();

                // get entry in given target locale (defaults to current locale)
                return !is_null($entry) ? $entry->in($locale->value) : null;
            }
        );
    }
This piece of code is ran the moment I hit the /en/servicedesk url.
$collections in this case can be either an Enum with a single value, or an array. In this example I've already made sure that it's a single string, namely dynamic_pages.
However when I check the performance for this in the Laravel debug bar, I see that there are SELECT * FROM entries WHERE collection = ... ; for almost all my collections.
Furthermore there are a lot of duplicate queries that seem to try to get the origin of a specific entry (that I am not even querying).
I am going to share examples below, what I wanna know though it, why is this happening? Am I doing something wrong?
The query it does correctly;

The unnecessary (I think) queries;

A lot of duplicates;


Coming from

**Comment by geertjanknapen1** [comment]
> There are open PRs to resolve both of these. On 10 May 2023, at 15:26, Geert-Jan Knapen ***@***.***> wrote:﻿ I have a piece of code that gets me a certain collection entry, it looks as follows: public function getCollectionEntry(Page|string $slug, Collection|array $collection, ?Locale $locale = null): ?EloquentEntry { $locale = getLocaleEnum($locale); $slugValue = is_string($slug) ? $slug : $slug->value; $collections = is_array($collection) ? collect($collection)->pluck('value')->toArray() : [$collection->value]; $cacheTags = $this->prepareCacheTags($collection); return Cache::tags($cacheTags)->remember( "get_collection_entry:{$locale->value}:$slugValue" . implode('-', $collections), config('custom.caching.ttl'), function () use ($slugValue, $locale, $collections) { /** @var EntryQueryBuilder $entryQueryBuilder */ $entryQueryBuilder = EntryFacade::query(); $entry = $entryQueryBuilder ->whereIn('collection', $collections) ->where('slug', $slugValue) ->where('published', true) ->first(); // get entry in given target locale (defaults to current locale) return !is_null($entry) ? $entry->in($locale->value) : null; } ); } This piece of code is ran the moment I hit the /en/servicedesk url. $collections in this case can be either an Enum with a single value, or an array. In this example I've already made sure that it's a single string, namely dynamic_pages. However when I check the performance for this in the Laravel debug bar, I see that there are SELECT * FROM entries WHERE collection = ... ; for almost all my collections. Furthermore there are a lot of duplicate queries that seem to try to get the origin of a specific entry (that I am not even querying). I am going to share examples below, what I wanna know though it, why is this happening? Am I doing something wrong? The query it does correctly; The unnecessary (I think) queries; A lot of duplicates; Coming from —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Can you point me to them?

**Comment by ryanmitchell** [comment]
And https://github.com/statamic/eloquent-driver/pull/124 I think is the other that is relevent

**Comment by geertjanknapen1** [comment]
Right, I think those were created due to my original issue back in January. Is there a timeline regarding when these get actually implemented?

We decided to continue work on other parts first and ignore the issue for a bit, but right now it's such a big problem that we are unable to properly continue our work so some sort of indication would be a lifesaver for me.

**Comment by ryanmitchell** [comment]
Not something I control I’m afraid. You can pull them in using composer patches if they are a show stopper for you.

**Comment by geertjanknapen1** [comment]
I was indeed thinking to implement some composer/vendor patches, however, that solution is not as clean as I would like it to be, hence I was asking for a timeline. But I appreciate the quick replies and clear answers, thanks!
