### ISSUE TITLE
add prefix to auth tables

### ISSUE THREAD

**Issue by goellner** [statamic/eloquent-driver#152]
would be great if the `role_user` and `group_user` table would get prefixed too, as it is only used by the statamic auth and not the whole laravel app. maybe the `password_activation_tokens` table too

**Comment by ryanmitchell** [comment]
These tables arent used in eloquent driver? User-driven database functions happen over in statamic/cms

**Comment by jasonvarga** [comment]
Yup. That happens in the core. You can adjust your migrations to include whatever prefix you want, and then adjust the configs appropriately.

- https://github.com/statamic/statamic/blob/d533b93ec460b05a8fc46aa138a7cfc7b4437f5c/config/auth.php#L107

- https://github.com/statamic/statamic/blob/d533b93ec460b05a8fc46aa138a7cfc7b4437f5c/config/statamic/users.php#L121-L122
