### ISSUE TITLE
Existing UUIDs are not used

### ISSUE THREAD

**Issue by marcusand** [statamic/eloquent-driver#16]
Hi!

I tried to migrate my data from an existing site into the db following the instructions from the readme.
It seems like the `UuidEntryModel` creates new Ids? That, to me, fails the purpose of preserving existing relations.

I replaced line 17 

``` php
$entry->{$entry->getKeyName()} = (string) Str::uuid();
``` 
with
``` php
$entry->{$entry->getKeyName()} = (string) $entry->getAttribute('id');
``` 

and now its fine. 

Is this a bug or did I miss something?

**Comment by phpsa** [comment]
Yep ran in to the same issue and put a pull request in for this - messes with simple-commerce shopping cart.

**Comment by FrankPeters** [comment]
Great, I hope it will be merged soon. Having the same issue.

**Comment by jesseleite** [comment]
Fixed in https://github.com/statamic/eloquent-driver/pull/19.
