### ISSUE TITLE
Split form config from submissions config

### ISSUE THREAD

**Issue by ryanmitchell** [statamic/eloquent-driver#164]
If https://github.com/statamic/cms/pull/6455 merges then the config for forms should split out the submissions model in a similar manner to https://github.com/statamic/eloquent-driver/pull/133 allowing the form config and submissions to be stored in different repositories.

**Comment by duncanmcclean** [comment]
Closing since this has been completed in #177 (GitHub hasn't auto-closed this since it didn't merge into the default branch).
