### ISSUE TITLE
Split variables config from global sets config

### ISSUE THREAD

**Issue by ryanmitchell** [statamic/eloquent-driver#172]
It would be nice to be able to store the set config in a different repository to the variables (eg files for set, eloquent for storage) but its not currently possible as core treats them as the same entity.

**Comment by ryanmitchell** [comment]
Yes. You’ll see there is a PR for splitting what is possible right now. This issue (and the other for forms) is just to highlight what needs done once statamic core allows for it.

**Comment by morphsteve** [comment]
Ah I see, sorry. Thanks for clarifying :)
