### ISSUE TITLE
Migration update could potentially cause duplicate issues

### ISSUE THREAD

**Issue by phadaphunk** [statamic/eloquent-driver#181]
This was added recently 

```
class AddBlueprintToEntriesTable extends UpdateScript
{
    public function shouldUpdate($newVersion, $oldVersion)
    {
        return ! Schema::hasColumn(config('statamic.eloquent-driver.table_prefix', '').'entries', 'blueprint');
    }
```

Now if someone pulls our repo and `composer update` before running the migration, a new migration (duplicate) will be created because he does not yet have this column. This could lead to someone potentially pushing duplicate migrations to a server and making it crash on deploy...

![image](https://github.com/statamic/eloquent-driver/assets/9636082/76084cd7-fce7-404b-95db-bcc6be88d1b7)

Shouldn't the update check look for the migration file in the project instead of looking if the column already exists?

**Comment by ryanmitchell** [comment]
Would it not make more sense for you to just not git commit the migration?

**Comment by phadaphunk** [comment]
@ryanmitchell 

All of our migrations are source controlled, and we wouldn't want to start manually picking which should be source controlled and which should not, since all the other ones have always worked fine.

**Comment by phadaphunk** [comment]
@ryanmitchell Probably the first time someone actually updates and pushes without migrating locally which created the duplicate.

**Comment by maxi032** [comment]
wrapp it in a 
```
if (!Schema::hasColumn('entries', 'blueprint')){ ?

````
}
```

**Comment by ryanmitchell** [comment]
@maxi032 yes that would work but again the issue is bigger. If migrations are being applied properly there would be no need to do that. 

To ‘solve’ this we would need to apply similar to logic to all past and figure migrations which makes no sense to me.
