### ISSUE TITLE
Problem installing on a fresh statamic cms

### ISSUE THREAD

**Issue by maxi032** [statamic/eloquent-driver#186]
When I follow the instructions to install the package, at the point of running
```
php artisan vendor:publish --provider="Statamic\Eloquent\ServiceProvider" --tag=migrations
```

All migrations are copied except one:

 Copying file 
   ERROR  Can't locate path: myproject\vendor\statamic\eloquent-driver\src/../database/migrations/create_global_varaibles_table.php.stub>.

   Environment
Application Name: Laravel
Laravel Version: 10.14.1
PHP Version: 8.1.10
Composer Version: 2.4.1
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.10.0 Solo

Statamic Addons
statamic/eloquent-driver: 2.3.1

**Comment by ryanmitchell** [comment]
Thanks. There is already a PR open to fix this - see #185
