### ISSUE TITLE
Please don't load all asset infos , when call exists method of the Statamic\ Eloquent\ Assets\Asset

### ISSUE THREAD

**Issue by videni** [statamic/eloquent-driver#191]
Generate thumbnail for one image , it will  get  all image infos from aws s3, or alioss.

``
http://localhost:8000/cp/thumbnails/YXNzZXRzOjphX2ltb2xhX2NlcmFtaWNhX3N0aWxlX3N0aWxlX2dsXzYyNGNmLndlYnA=/small
``

which is extreamly slow, because it try to get all image infoes from remote aws s3, or alioss,  as you can see 
![image](https://github.com/statamic/cms/assets/4058341/fae8cffe-37bf-4fd0-8754-5b9134bde09b)

I have 50 thousand images, generating one thumbnai would halt my server for a long time.

**Comment by ryanmitchell** [comment]
This is the same approach taken by the file driver - https://github.com/statamic/cms/blob/f8fcb062488507c2dc96e96b8a2377ce8c5c7246/src/Assets/Asset.php#L200-L207

Due to the possibility of having containers file based and assets not (or the other way around) we can't do any clever database optimisations to check for existence.

I agree it's an issue, I just dont think it can be solved by this driver. I think you should open this issue over on statamic/cms and link to this conversation.

**Comment by videni** [comment]
@ryanmitchell Yes, you are right, Maybe the AssetContainer should add a exists method.

**Comment by ryanmitchell** [comment]
Just looping back to this. I suppose you could also bind your own Asset model that extends the eloquent one and overwrite the exists method yourself? Maybe make it query the database instead of the file system? You can define your asset in the config file.

```php

namespace App\Eloquent;

class Asset extends \Statamic\Eloquent\Assets\Asset {
   public function exists() { ... }
}

```

**Comment by videni** [comment]
@ryanmitchell , it is far more complex than what I expetected, lots of places will trigger the all methd of the AssetContainerContents class, the exists method is just one of them. I am afraid this would  not be resolved soon, most likely , it would take years.

**Comment by ryanmitchell** [comment]
Yes it will fetch and cache data, but it also indexes it, similar to a database (the Stache is basically a flat file database). But this driver bypasses the Stache and uses eloquent.

If you are hitting issues with performance using the eloquent driver we should definitely investigate ways to resolve those as long as we preserve compatibility with the behaviour from the Stache driver.

**Comment by SylvesterDamgaard** [comment]
I bind my own Asset model with an updated exists method,  which uses the meta table to check for existence. It made my frontpage 50% faster just by doing this. I know this will not work for everyone, but we never upload images directly to the disk, and don't want it displayed without metadata.

```php
public function exists()
{
    return Blink::once($this->containerHandle() .'::'. $this->metaPath(), function () {
        return AssetModel::where('handle', $this->containerHandle() .'::'. $this->metaPath())->exists();
    });
}
```
