### ISSUE TITLE
Using eloquent-driver makes pest tests throw NotFoundHttpException

### ISSUE THREAD

**Issue by aknEvrnky** [statamic/eloquent-driver#205]
Hi, this is a `bug report`.

# the problem

Any route related with statamic frontend is not working in testing stage. I tested with pest. Sample testing code:

```php
it('returns a successful response', function () {
    $this->withoutExceptionHandling();
    $response = $this->get('/');

    $response->assertStatus(200);
});
```

`Symfony\Component\HttpKernel\Exception\NotFoundHttpException: GET http://localhost:8000`

## how to reproduce this error?

- Create fresh statamic app using statamic/cli
- replace phpunit with pest (this step could be optional, it might be reproduced with phpunit)
- run example test. It passes.
- install statamic/eloquent driver
- recreate homepage from control panel
- try to run test again. it could not resolve the path.

**Comment by aknEvrnky** [comment]
I can clearly see either homepage or other pages in browser. Here is my curl response:

```
curl -I 127.0.0.1:8000                   
HTTP/1.1 200 OK
Host: 127.0.0.1:8000
Date: Thu, 21 Sep 2023 10:21:58 GMT
Connection: close
X-Powered-By: PHP/8.2.7
Cache-Control: no-cache, private
Date: Thu, 21 Sep 2023 10:21:58 GMT
Content-Type: text/html; charset=UTF-8
Permissions-Policy: interest-cohort=()
X-Powered-By: Statamic

```

**Comment by ryanmitchell** [comment]
Ok, and did you populate your testing db with any data? Do you have a seeder or factories of any sort?

**Comment by aknEvrnky** [comment]
Good question, I think the issue is using a memory db with RefreshDatabase trait causes that. Since my entries are stored in my actual db it must throw the exception as it should be.

Thanks for your attention. Issue can be closed.
