### ISSUE TITLE
Revisions will not work after upgrading to Statamic v4.41.0

### ISSUE THREAD

**Issue by helloiamlukas** [statamic/eloquent-driver#229]
Statamic v4.41.0 introduced the following bugfix: https://github.com/statamic/cms/pull/9190
Unfortunately this breaks the revision functionality when using the eloquent driver.

Revisions are now loaded via the `id` attribute: https://github.com/statamic/cms/pull/9190/commits/8c3275a97c22a9a6bfe58d076cc64435d8c2e7fd

This attribute is not saved when using the eloquent driver:
https://github.com/statamic/eloquent-driver/blob/6eccbb6d477df3de1759bd3a70a0fdc85e2ee9a8/src/Revisions/Revision.php#L53

@ryanmitchell What's the reason for this? Can we add the `id` to the attributes without any further sideeffects?

**Comment by ryanmitchell** [comment]
I've opened https://github.com/statamic/eloquent-driver/pull/230 to start storing id again. Im not sure why we weren't in the first place.

Unfortunately due to how the change has been made in core any old revisions will now be broken.

**Comment by helloiamlukas** [comment]
Great, thank you! :)

> Unfortunately due to how the change has been made in core any old revisions will now be broken.

What do you think about making a migration/command, that will extract the id from the key and add it to the attributes?

**Comment by helloiamlukas** [comment]
Done! https://github.com/statamic/eloquent-driver/pull/231
