### ISSUE TITLE
Separator for namespace and handle for Blueprints

### ISSUE THREAD

**Issue by andreas-eisenmann** [statamic/eloquent-driver#237]
In statamic/cms whe have `::` as separator for namespace and handle when loading a blueprint, see [this line](https://github.com/statamic/cms/blob/4e595a8a7327ae06c64fa2560718b7328fe89751/src/Fields/BlueprintRepository.php#L35).

So we can call:

```php
\Statamic\Facades\Blueprint::find("foo::bar");
```

Now "foo" is treated as namespace and "bar" as the handle.

Let's peek into the counterpart in statamic/eloquent-driver at [this line](https://github.com/statamic/eloquent-driver/blob/38b3645fbdd2470918690a4a5ef0156b7b140fc9/src/Fields/BlueprintRepository.php#L106). Here we are not able to use `::` as a separator, but instead we have to use the dot `.` es separator.

We use statamic-rad-pack/runway in combination with statamic/eloquent-driver, so we store our blueprints in the database.

[This](https://github.com/statamic-rad-pack/runway/blob/71e167bbe303ee19f9597555bd83a87a3a88ea99/src/Resource.php#L52) code won't work with the eloquent driver:

```php
    public function blueprint(): Blueprint
    {
        $blueprint = Blueprint::find("runway::{$this->handle}");

        if (! $blueprint) {
            $blueprint = Blueprint::make($this->handle)->setNamespace('runway')->save();
        }

        return $blueprint;
    }
```

`$blueprint` will always be `null`. If we call `Blueprint::find("runway.{$this->handle}");` (so with a dot as the separator), everything works fine.

Just spent a few seconds to think about in which project to report this issue, but for me it seems clear that if statamic/cms supports `::` as a separator to distinguish between namespace and handle when loading a blueprint, the eloquent driver should also support this behaviour to stay compatible? Developers should rely on that if they use a Facade of statamic (e.g. `\Statamic\Facades\Blueprint`) in their app code and switch to the eloquent driver that everything works the same as before.

**Comment by ryanmitchell** [comment]
I've opened a PR here - https://github.com/statamic/eloquent-driver/pull/238
let me know if this works as expected

**Comment by andreas-eisenmann** [comment]
Thanks for the fast reply! 🚀

Yes, this would work generally, but there's a little syntax error (`)` instead of `]`). 

And I think you could shrink it to:

```php
        if (str_contains($blueprint, '::')) {
            return explode('::', $blueprint);
        }
```

**Comment by ryanmitchell** [comment]
Already fixed that
