### ISSUE TITLE
Call to a member function isFuture() on int 

### ISSUE THREAD

**Issue by freshface** [statamic/eloquent-driver#24]
Got this error after installing it to an existing site. https://flareapp.io/share/KPgnE8gm
Migration went ok. I can see the entries in the database.

This is my statamic-eloquent-drive.php config:

```
return [

    'entries' => [
        'model' => \Statamic\Eloquent\Entries\UuidEntryModel::class,
    ],

];
```

**Comment by freshface** [comment]
Update: the date field in entries table are empty.

**Comment by jesseleite** [comment]
@freshface There were some `date` and `UuidEntryModel` related fixes in https://github.com/statamic/eloquent-driver/pull/29. Could you confirm if this is still an issue, and if not provide more info for us to reproduce your issue? Thanks!

**Comment by ryanmitchell** [comment]
Does this still exist in v1? If so, can you provide a sample repository showing the issue?

**Comment by ryanmitchell** [comment]
@freshface I'm going to close this due to inactivity. If you still have the issue please feel free to re-open.
