### ISSUE TITLE
Eloquent Driver not supporting taxonomies, navigations, globals, or form submissions

### ISSUE THREAD

**Issue by ashishnjoshi** [statamic/eloquent-driver#25]
Hello Team,

I want to implement Statamic Eloquent Driver in my current existing statamic project, But I've found that this is not supporting taxonomies, navigations, globals, or form submissions. 

I want to use Eloquent Driver in all above points, So Can you please provide me any solution for same.

Please let me know in case any other details required.

Waiting for your reply, Please provide me ASAP

**Comment by duncanmcclean** [comment]
Someone's opened a pull request for this, which is still currently in draft mode. See #20
