### ISSUE TITLE
Assets gets duplicated when there is at least one capital letter in the name

### ISSUE THREAD

**Issue by shawinigan** [statamic/eloquent-driver#258]
We try tu upload assets from the CP but they gets inserted in double in the database when there's a capital letter in the name of the file.  We just renamed the file and here's the behaviour : 

billethackqc.pdf  => working fine
billethackqc1.pdf => working fine
billethackqc_1.pdf => working fine
billethackqc_111111111111111111111111111111111111111111111111111111111.pdf => working fine
billethackqc_1Allo.pdf => get inserted in double

Again, it was the same pdf file, we only renamed it and got this behaviour. It seems any file with a capital letter is having the same issue.

**Comment by ryanmitchell** [comment]
Whats the value of `statamic.config.assets.lowercase` ?

**Comment by shawinigan** [comment]
'lowercase' => true,

**Comment by ryanmitchell** [comment]
Thanks, I'll spent some time later in the week seeing if I can replicate this.

**Comment by ryanmitchell** [comment]
I don't seem to be able to replicate this using a local filesystem. What filesystem are you using?

**Comment by modrictin** [comment]
Hey there,

If I try to save an asset which contains a whitespace to `assets_meta` table, I get the following error:
```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'one-public-im-az-1710414015.png' for key 'assets_meta.assets_meta_container_folder_basename_unique' (Connection: mysql, SQL: update `assets_meta` set `basename` = im-az-1710414015.png, `filename` = im-az-1710414015, `path` = public/im-az-1710414015.png, `meta` = {"data":[],"size":861322,"last_modified":1710414015,"width":897,"height":673,"mime_type":"image\/png","duration":null}, `assets_meta`.`updated_at` = 2024-03-14 11:00:15 where `id` = 20)
```

I also get 2 entries saved to my database after the error:
![image](https://github.com/statamic/eloquent-driver/assets/31577031/0b517c79-26e6-4405-97e7-1248b8b78612)

Maybe it is connected to this.

Thanks in advance,
Tin

**Comment by ryanmitchell** [comment]
@modrictin can you verify you are on the latest version (3.3.2) as I'm not seeing this behaviour there. How are you creating assets?

**Comment by shawinigan** [comment]
> I don't seem to be able to replicate this using a local filesystem. What filesystem are you using?

Here's the config in the filesystem along with the part related to it in the .env file

 'documents' => [
            'driver' => ENV('LOCAL_FILE_DRIVER', 'local'),
            'host' => ENV('LOCAL_FILE_HOST', ''),
            'username' => ENV('LOCAL_FILE_USERNAME', ''),
            'password' => ENV('LOCAL_FILE_PASSWORD', ''),
            'visibility' => 'private',
            'directory_visibility' => ENV('LOCAL_FILE_DIRECTORY_VISIBILITY', ''),
            'root' => ENV('LOCAL_FILE_ROOT', storage_path('app')).'/documents',
            'throw' => ENV('LOCAL_FILE_THROW', false)
        ],

LOCAL_FILE_DRIVER=sftp
LOCAL_FILE_HOST=10.1.4.151
LOCAL_FILE_USERNAME=************
LOCAL_FILE_PASSWORD=************
LOCAL_FILE_VISIBILITY=public
LOCAL_FILE_DIRECTORY_VISIBILITY=public
LOCAL_FILE_ROOT=/var/www/projects/intranet/intranet.dev.shawinigan.ca/storage/app/
LOCAL_FILE_THROW=true

**Comment by ryanmitchell** [comment]
@shawinigan are you uploading assets through the control panel or by another method? Can you confirm you are using the latest version of this driver?

**Comment by shawinigan** [comment]
I am uploading through the CP and ran a composer update yesterday so we're running version 3.3.2 now. Here's the part of the composer.lock file about eloquent-driver


`{
            "name": "statamic/eloquent-driver",
            "version": "v3.3.2",
            "source": {
                "type": "git",
                "url": "https://github.com/statamic/eloquent-driver.git",
                "reference": "3e19212e1ad1abeee0abd9f1afba98f8caf5729c"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/statamic/eloquent-driver/zipball/3e19212e1ad1abeee0abd9f1afba98f8caf5729c",
                "reference": "3e19212e1ad1abeee0abd9f1afba98f8caf5729c",
                "shasum": ""
            },
            "require": {
                "php": "^8.0",
                "statamic/cms": "^4.51"
            },
            "require-dev": {
                "doctrine/dbal": "^3.3",
                "laravel/pint": "^1.0",
                "orchestra/testbench": "^7.0 || ^8.0",
                "phpunit/phpunit": "^9.4"
            },
            "type": "library",
            "extra": {
                "statamic": {
                    "name": "Eloquent Driver",
                    "description": "Allows you to store Statamic data in a database."
                },
                "laravel": {
                    "providers": [
                        "Statamic\\Eloquent\\ServiceProvider"
                    ]
                }
            },
            "autoload": {
                "psr-4": {
                    "Statamic\\Eloquent\\": "src"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "description": "Allows you to store Statamic data in a database.",
            "support": {
                "issues": "https://github.com/statamic/eloquent-driver/issues",
                "source": "https://github.com/statamic/eloquent-driver/tree/v3.3.2"
            },
            "time": "2024-03-11T10:57:32+00:00"
        },`

**Comment by shawinigan** [comment]
I receive an empty array

> Interesting, as I said I'm struggling to recreate.
> 
> If you do a dump after this line -
> 
> https://github.com/statamic/eloquent-driver/blob/3e19212e1ad1abeee0abd9f1afba98f8caf5729c/src/Assets/Asset.php#L151
> 
> - do you get any values in $original?

**Comment by ryanmitchell** [comment]
If you add:

$source->syncOriginal();

after this line does it fix it?

https://github.com/statamic/eloquent-driver/blob/3e19212e1ad1abeee0abd9f1afba98f8caf5729c/src/Assets/Asset.php#L172

**Comment by shawinigan** [comment]
> If you add:
> 
> $source->syncOriginal();
> 
> after this line does it fix it?
> 
> https://github.com/statamic/eloquent-driver/blob/3e19212e1ad1abeee0abd9f1afba98f8caf5729c/src/Assets/Asset.php#L172

No, it still gets duplicated in the DB

**Comment by modrictin** [comment]
Hey @ryanmitchell ,

yes, I can confirm:
![image](https://github.com/statamic/eloquent-driver/assets/31577031/1cb500a3-dbe6-4e78-9d11-27d84f276dc0)

All the best,
Tin

**Comment by ryanmitchell** [comment]
It seems bringing back syncOriginal on upload from before https://github.com/statamic/eloquent-driver/issues/251 fixes this, so I'll need to find a way of solving that issue without it causing these duplications.

**Comment by potsky** [comment]
Hi @ryanmitchell, we have the same problem:

- We use S3 to store files
- We have lowercase set to true
- It happens only when there is a space in the name :
    - `burning-man-2011 edit.jpg` → 2 entries created in DB ans they are exactly the same except the ID of course 👎 
    - `burning-man-2011-edit.jpg` → 1 entry created in DB 👍 
- We have try your suggestions from last week (adding `$source->syncOriginal();`...) and nothing changes

According to the title, in fact it happens when the sanitized file name is not the same as the original one...

It was my poor contribution!

**Comment by ryanmitchell** [comment]
@potsky see if https://github.com/statamic/eloquent-driver/pull/259 fixes it
