### ISSUE TITLE
Reorder collection does not working

### ISSUE THREAD

**Issue by potsky** [statamic/eloquent-driver#260]
Hi !

We have the same problem as in https://github.com/statamic/eloquent-driver/issues/43 but with version 3.3.2 on Statamic 4.54.0.
`updated_at` field of the reordered entries is not touched.

https://github.com/statamic/eloquent-driver/assets/408237/601045e1-428a-4965-a143-0c6bafb168da

**Comment by ryanmitchell** [comment]
@jasonvarga this is the issue I mentioned a while back (similar to https://github.com/statamic/eloquent-driver/issues/220) that comes from collections and entries being on split configurations.

When the order is saved the Stache collection tree is being updated, not the order column on the entry model, so the entry is never updated.

I'm not sure that this can be solved without changes in core?
