### ISSUE TITLE
Duplicated Queries all the way

### ISSUE THREAD

**Issue by MazzMazz** [statamic/eloquent-driver#262]
I have a Landingpage with 4 Entries - nothing else. A Author is linked, also a Category and Image.

The problem I am facing is that a looooot of queries are executed, and i have no clue where to fix this, include a Cache or smth. I need a hint or something - there are 158 Queries for 4 Blogposts.

```
158 statements were executed, 130 of which were duplicates, 28 unique.
```
<img width="1110" alt="image" src="https://github.com/statamic/eloquent-driver/assets/10706512/a6696376-e0ed-4912-a3d0-aa5f745fe61d">

<img width="880" alt="image" src="https://github.com/statamic/eloquent-driver/assets/10706512/3bb9ab21-2965-40be-9c51-16377a1bf39d">

**Comment by ryanmitchell** [comment]
Can you please paste the contents of `php please support:details` ?

Are you using an entries field type?

**Comment by MazzMazz** [comment]
**php please support:details**

```
Navigations: file
Revisions: eloquent
Taxonomies: eloquent
Terms: eloquent
```

Yess the Author is a Entries Field Type.

**Comment by ryanmitchell** [comment]
Yep, so you're seeing the result of the queries from augmentation on the entries field type (I believe):
https://github.com/statamic/cms/blob/08512240a30112a0dcf658385d404caad4d6cf0a/src/Fieldtypes/Entries.php#L329-L340

I'm hopeful some of the performance improvements coming in v5 of core will reduce the duplicate queries.

**Comment by MazzMazz** [comment]
Yes for the Entries this might be true - at least the Fieltypes/Entries in in the Backtrace
<img width="892" alt="image" src="https://github.com/statamic/eloquent-driver/assets/10706512/a2daeca0-c6cc-4f67-b72d-7a63f2f38699">

However would this be the same for e.g. Assets and Taxonomies
<img width="993" alt="image" src="https://github.com/statamic/eloquent-driver/assets/10706512/3237cdd1-c3be-49da-bb0c-205664505407">

<img width="1034" alt="image" src="https://github.com/statamic/eloquent-driver/assets/10706512/35883e20-ef4c-4702-bd1f-6928777db75a">

**Comment by ryanmitchell** [comment]
Yes, the field types all work the same way and currently don't cache their query results.

**Comment by MazzMazz** [comment]
Allrighty - thank you for the explanation. Any known workaround or just wait for Statamic5? 😄

**Comment by MazzMazz** [comment]
Allrighty - thank you. Much apprechiated 🙏🏻

**Comment by clementmas** [comment]
Has this issue been fixed with Statamic v5? I'm still seeing hundreds of queries for each page including duplicate `assets_meta` queries like this one repeated 7 times:

```sql
select * from `assets_meta` where `container` = '{\"id\":\"assets\",\"title\":\"Assets\",\"handle\":\"assets\",\"disk\":\"s3\",\"blueprint\":{\"title\":\"Asset\",\"handle\":\"assets\"},\"search_index\":null,\"api_url\":null}' and `path` in ('my-filename.jpg')
-- EloquentQueryBuilder.php#58
```

```
Asset Containers: file
Assets: eloquent
```

**Comment by ryanmitchell** [comment]
No it hasn’t. How the asset field would need to be changed in core - we can’t fix it on the driver side.

**Comment by MazzMazz** [comment]
@clementmas i took a quick look at Statamic5 for my project when it was released and i also still have a looot of duplicate queries. I even thought the site was slower after the upgrade 😅 So it's currently still running on Statamic4.

Since my job is quite demanding currently I wasn't able to check if it may be a config problem on my side from the upgrade or investigate further/give more details about the problem/recreate or replicate the issue in a new Repo for the devs.

**Comment by ryanmitchell** [comment]
I've chatted this through a bit both on the core side and the antlers side and the solution for now is to assign the value to a variable eg {{ $my_field = my_field }} - this will ensure the parser gets and caches the value.

As its already blinking the result of max_items: 1 fields ([see PR](https://github.com/statamic/cms/pull/9938)) this only is needed for fields that aren't max_items: 1
