### ISSUE TITLE
Eloquent Sites

### ISSUE THREAD

**Issue by mwagena** [statamic/eloquent-driver#320]
### Description

Is it possible to have sites implemented in the driver? Since the release of Statamic 5 the sites are managed through a YAML file in the contents directory.

**Comment by ryanmitchell** [comment]
Working on this here: https://github.com/statamic/eloquent-driver/pull/322

**Comment by mwagena** [comment]
hi @ryanmitchell 
Thanks quick for the implementation!

There seems to be an issue with the setup when changing the driver set to 'eloquent' but without running the migration file to create the sites table.
eg. php artisan tinker gives the following error
```  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_name.sites' doesn't exist (Connection: mysql, SQL: select * from `sites`)```
This isn't an issue with other drivers for example for Taxonomies.

**Comment by ryanmitchell** [comment]
I don't see that as an issue - you need to publish and run the migrations before switching the driver on an existing install.

**Comment by mwagena** [comment]
Hi,
Well actually this is an issue when implementing in an (already) live existing environment.
Typically this change would be deployed as one common change (updated config file from file to eloquent in combination with the migration file in place). The migration (php artisan migrate) though can't be ran because somewhere in the code there is a expectation that the table already is existing.

**Comment by ryanmitchell** [comment]
I understand, but it's still an issue in dev-ops land more than this driver. 
You could deploy with the migration, then later do a further deploy with the config change.
