### ISSUE TITLE
CollectionRepository does not use custom models

### ISSUE THREAD

**Issue by isarphilipp** [statamic/eloquent-driver#33]
The driver allows to specify a different `EntryModel` in `config/statamic-eloquent-driver.php` by setting `entries.model`.

![image](https://user-images.githubusercontent.com/9417412/138111297-b983a70a-c799-4d24-bb63-acfa77cdf1e7.png)

However, the `CollectionRepository` is currently hardcoded to use the shipped EntryModel:

![image](https://user-images.githubusercontent.com/9417412/138111440-04bf59c0-d3a8-489b-8e83-df7ce5ba63d3.png)

This leads to errors when updating entries. A PR will be provided to fix it.

**Comment by ryanmitchell** [comment]
Can you check this against v1? I think this issue can be closed.
