### ISSUE TITLE
Statamic shows old version in their marketplace

### ISSUE THREAD

**Issue by georgecoca** [statamic/eloquent-driver#331]
### Bug description

Current version of this package is: v4.12.0
Statamic market place version is: v4.11.1

https://statamic.com/addons/statamic/eloquent-driver

### How to reproduce

Check here: https://statamic.com/addons/statamic/eloquent-driver

### Environment

```yaml
No env needed
```

**Comment by duncanmcclean** [comment]
Thanks for letting us know, it should be fixed now!
