### ISSUE TITLE
Save custom form config fields to database

### ISSUE THREAD

**Issue by gregdev** [statamic/eloquent-driver#341]
### Description

The ability to add additional config fields to forms was added in https://github.com/statamic/cms/pull/8491. When using the eloquent driver for forms, any custom fields aren't added to the database.

It would be amazing if these fields were included in the `settings` column in the `forms` table.

**Comment by ryanmitchell** [comment]
Thanks for the reminder - see: https://github.com/statamic/eloquent-driver/pull/342

**Comment by gregdev** [comment]
Now that's impressive service! Thank you kind sir.
