### ISSUE TITLE
Performance Issues with Entry and Taxonomy Relationship

### ISSUE THREAD

**Issue by michaeljhopkins** [statamic/eloquent-driver#344]
I believe this is related to [this issue](https://github.com/statamic/cms/issues/10286)

## Background 

Tossing some more information towards this issue as I believe it's related (possibly to [this issue](https://github.com/statamic/cms/issues/10295) as well).

We have 19k blog `Posts` that each have a `Category` taxonomy. When viewing the blog post, if the page had `categories:title` anywhere in the html it would take a long time to load. Using debugbar it said there were roughly 19k `UuidEntryModel` models loaded. Clearly the source of the slowness

Removing `categories:title` from the page would make the page snappy again.

In the `content/collections/Posts.yaml` file was the below block of code

```
taxonomies:
  - categories
``` 

## Fix

Removing the above block of code makes all the pages snappy once more. I suspect because the below code is in `resources/blueprints/collections/posts/post.yaml` is why pulling the `title` or `slug` still works in antlers templates

```
-
  handle: categories
  field:
    type: terms
    taxonomies:
      - categories
    display: Category
    max_items: 1
    mode: select
```

# New Issue

This introduces a new issue however. Because the collection no longer has "access" to the categories taxonomy, you are unable to manage that data in the control panel. I think this issue should be reopened and looked at

_Originally posted by @michaeljhopkins in https://github.com/statamic/cms/issues/10286#issuecomment-2303160082_

**Comment by swen4** [comment]
@ryanmitchell In case you haven't found a solution yet, my workaround might be of help until this issue is fixed. https://github.com/statamic/eloquent-driver/issues/343#issuecomment-2312004100

**Comment by ryanmitchell** [comment]
@michaeljhopkins https://github.com/statamic/eloquent-driver/pull/345 - does this help any?

**Comment by michaeljhopkins** [comment]
Rad!! I'll give it a test

**Comment by michaeljhopkins** [comment]
@ryanmitchell this branch fixes my issue! Once it's merged in feel free to close this ticket
