### ISSUE TITLE
Optimize taxonomy queries.

### ISSUE THREAD

**Issue by TheBnl** [statamic/eloquent-driver#373]
### Description

Writing this here to check if this is wanted behaviour or not. The issue I was facing is that on a project with 100+ tags I saw the total amount of page queries reflecting that amount. Diving deeper into where these queries where coming from I traced it back to the TermQueryBuilder. In the method `applyCollectionAndTaxonomyWheres` that is used when retrieving page taxonomies, a map is run over all taxonomies to check when they are used on the page. This creates, in my case, 134 count queries being fired on every page request. The result is only cached in the blink request cache.  

The current query:
```php
$query = TermModel::where('taxonomy', $taxonomy)
    ->select('slug')
    ->get()
    ->map(function ($term) use ($taxonomy) {
        return Entry::query()
            ->whereIn('collection', $this->collections)
            ->whereJsonContains('data->'.$taxonomy, [$term->slug])
            ->count() > 0 ? $term->slug : null;
    })
    ->filter()
    ->values();
```

The reason is, probably, that someone can configure the Entries to be stored with the file driver. 

My suggestion would be to check what entry driver is configured and based on that opt for a join to come to the result reducing the 133 queries to 1.

Suggestion:
```php
if (config('statamic.eloquent-driver.entries.driver', 'file') == 'eloquent') {
    $query = TermModel::where('taxonomy', $taxonomy)
        ->join('entries', function (JoinClause $join) use ($taxonomy) {
            $join->on('entries.collection', '=', 'entries.collection')
                ->where('entries.collection', $this->collections)
                ->whereRaw("json_contains(`entries`.`data`, concat('[\"',`taxonomy_terms`.`slug`,'\"]'), '$.\"$taxonomy\"')");
        })
        ->select('taxonomy_terms.slug')
        ->get();
} else {
    $query = TermModel::where('taxonomy', $taxonomy)
        ->select('slug')
        ->get()
        ->map(function ($term) use ($taxonomy) {
            return Entry::query()
                ->whereIn('collection', $this->collections)
                ->whereJsonContains('data->'.$taxonomy, [$term->slug])
                ->count() > 0 ? $term->slug : null;
        })
        ->filter()
        ->values();
}
```
I must admit that this join is a bit funky, especially the on statement `'entries.collection', '=', 'entries.collection'` but it gets the job done. Definitely open to suggestions to optimize or replace it with something better.
But in the end the N+1 query issue could definitely be solved.

**Comment by ryanmitchell** [comment]
I agree the query could be improved but I'm not sure this is the right approach, as it's too opinionated. For example, what if someone has their own repository they are using thats not files or eloquent, or if they have bound their own models.

I would like to see pivot table between terms and entries - that would be the right way to fix this I feel.

**Comment by ryanmitchell** [comment]
Your current code only works for your specific taxonomy names, it would need to be made generic. It's possible to do, but as I said it's not the right approach here.

**Comment by ryanmitchell** [comment]
Yes sorry I meant table names. If you want to open a PR with the changes and some tests then I can review it properly.

**Comment by TheBnl** [comment]
I have a draft PR in the works see #376 .

```php
$enrtiesTable = (new EntryModel)->getTable();
$termsTable = (new TermModel)->getTable();
$query = TermModel::where('taxonomy', $taxonomy)
    ->join($enrtiesTable, function (JoinClause $join) use ($taxonomy, $enrtiesTable, $termsTable) {
        // TODO: make Expression db driver independent
        $columnExpression = new Expression("JSON_QUOTE({$termsTable}.slug)");
        $join->on("{$enrtiesTable}.collection", '=', "{$enrtiesTable}.collection")
            ->where("{$enrtiesTable}.collection", $this->collections)
            ->whereJsonContains("{$enrtiesTable}.data->{$taxonomy}", $columnExpression);
    })
    ->select('taxonomy_terms.slug')
    ->pluck('slug');
```

The query now uses the dynamic table names. Problem is in the `Expression` that is now using `JSON_QUOTE`. First i was using `CONCAT` to get the joined slug value in a manner that it could be parsed by `JsonContains`. But using `JSON_QUOTE` felt a bit cleaner. However using either `JSON_QUOTE` or `CONCAT` is assuming the DB driver is MySQL. And the implementation should be able to support, at least, the drivers used by Laravel.

I'll come back to it when i have some more time to put into finding an alternative to the current Expession.

**Comment by ryanmitchell** [comment]
You can get the engines grammar and wrap the column- see: https://github.com/statamic/eloquent-driver/blob/01b187ddb984b95d4ae3f7abfea7108edcd1999f/src/Entries/EntryQueryBuilder.php#L60

**Comment by TheBnl** [comment]
The wrapping was not the issue, but it is still good to do of course, the issue is with the `JSON_QUOTE` method, that seems to behave differently in sqlite. Might also be the difference in the resulting queries.

MySQL
```sql
select `taxonomy_terms`.`slug` from `taxonomy_terms` 
inner join `entries` on `entries`.`collection` = `entries`.`collection` 
and `entries`.`collection` in (?)
and json_contains(`entries`.`data`, JSON_QUOTE(`taxonomy_terms`.`slug`), '$."tags"') 
where `taxonomy` = ?
```

SQLite
```sql
select "taxonomy_terms"."slug" from "taxonomy_terms" 
inner join "entries" on "entries"."collection" = "entries"."collection" 
and "entries"."collection" in (?)
and exists (select 1 from json_each("entries"."data", '$."tags"') where "json_each"."value" is JSON_QUOTE("taxonomy_terms"."slug")) 
where "taxonomy" = ?
```

With json_quote works in MySQL.
```
$columnExpression = new Expression("json_quote({$wrappedColumn})");
```
Without json_quote passes the tests using SQLite.
```
$columnExpression = new Expression("{$wrappedColumn}");
```

I could conditionally add the json_quote when the driver is mysql, but I don't prefer that approach.

**Comment by TheBnl** [comment]
With conditionally checking for the driver and making the required adjustments the query now looks likt this:
```php
$entriesTable = (new EntryModel)->getTable();
$termsTable = (new TermModel)->getTable();
$query = TermModel::where('taxonomy', $taxonomy)
    ->join($entriesTable, function (JoinClause $join) use ($taxonomy, $entriesTable, $termsTable) {
        $wrappedColumn = $join->getGrammar()->wrap("{$termsTable}.slug");
        $column = match (DB::getDriverName()) {
            'mysql' => "json_quote({$wrappedColumn})",
            'pgsql' => "to_jsonb({$wrappedColumn}::text)",
            default => $wrappedColumn,
        };
        $columnExpression = new Expression($column);
        $join->on("{$entriesTable}.collection", '=', "{$entriesTable}.collection")
            ->whereIn("{$entriesTable}.collection", $this->collections)
            ->whereJsonContains("{$entriesTable}.data->{$taxonomy}", $columnExpression);
    })
    ->select('taxonomy_terms.slug')
    ->pluck('slug');
```
`mariadb` supports the same syntax as `mysql` so i can combine those. The one missing in this setup is `sqlsrv`.
Other point to note is that the current testing setup only tests in sqlite so currently all checks pass. But this setup would probably break with an `sqlsrv` driver. 

Still need to test and implement the required changes for that driver, but am curious to your views regarding this approach. As a setup using a driver that is not in the match list would break. Because of that i'm not sure if this would be something that would be merged in the module.

**Comment by ryanmitchell** [comment]
I appreciate the work but I think we need to find a way without the match statement. 

We do some conditional checking elsewhere but it’s on a standard sql function that SQLite doesn’t support.

there will be a way of doing this using laravel methods. We just need to find it.

**Comment by ryanmitchell** [comment]
The other bigger issue is whereJsonContains() does an exact match, not an any match. So the current approach will actually not contain the correct results.

for example an entry has terms `one`, `two`, `three`, then `whereJsonContains('term_field', ['one', 'two'])` would not return that entry. 

the SQL would need to get the individual slugs then do a orWhereJsonContains() on each of them.

As you can see its not as simple as it first looks.

**Comment by TheBnl** [comment]
Gave it a spin with SQLite, but got the same execption that i had with the join + concat :
```
Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1 no such function: CONCAT (Connection: testing, SQL: 
```
```sql
select "slug" from "taxonomy_terms" where "taxonomy" = tags and exists (select 1 from "entries" where exists (select 1 from json_each("data", '$."tags"') where "json_each"."value" is CONCAT('"', taxonomy_terms.slug, '"'))))
```

I do like the whereExists approach tho, it mimics the behaviour of the generated sqlite query. 

The problem with laravels `whereJsonContains` method is that it not "natively" accepts dynamic values. So it's build with static values in mind. This can be circumvented by using an expression. But then we run into the issue of having the value be "json parsable" 🤔

**Comment by TheBnl** [comment]
True, I also used it on the initial suggestion, but noticed the exception being thrown while running the tests. I looked at it with a colleague of mine and we think it might be due to the version of sqlite that is used by the tests. I also tried the upper and lower case formatting.
