### ISSUE TITLE
Support multi-site

### ISSUE THREAD

**Issue by edalzell** [statamic/eloquent-driver#4]
Trying to convert a site to multisite via `php please multisite` results in:

```
  Call to a member function hydrate() on null

  at vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:548
    544▕      * @return \Illuminate\Database\Eloquent\Model[]|static[]
    545▕      */
    546▕     public function getModels($columns = ['*'])
    547▕     {
  ➜ 548▕         return $this->model->hydrate(
    549▕             $this->query->get($columns)->all()
    550▕         )->all();
    551▕     }
    552▕ 

      +2 vendor frames 
  3   app/Tables/EntryQueryBuilder.php:43
      Statamic\Query\EloquentQueryBuilder::get()

  4   app/Tables/CollectionRepository.php:29
      App\Tables\EntryQueryBuilder::get()

```

**Comment by jesseleite** [comment]
@edalzell Is this still an issue for you? I'm running a multisite eloquent setup here without issue 🤔

**Comment by edalzell** [comment]
> @edalzell Is this still an issue for you? I'm running a multisite eloquent setup here without issue 🤔

You mean you converted a site that uses the Eloquent driver to multi-site via the command and there were no issues?

**Comment by edalzell** [comment]
tbh though, I don't remember this so if you can't reproduce it, feel free to close

**Comment by jesseleite** [comment]
Yep, just tried both ways:

- Importing a stache multisite to DB using eloquent-driver
- Running `php please multisite` after already setup in the DB with eloquent-driver

Seems to work great now. Going to close the issue, but feel free to squawk if you run into this again.
