### ISSUE TITLE
Reorder collection does not working

### ISSUE THREAD

**Issue by enespolat24** [statamic/eloquent-driver#43]
Hey, i'm using statamic 3.2.37 with eloquent driver and i'm having this issue `https://github.com/statamic/cms/issues/3620`

any idea how to solve this ?

**Comment by simonbedard12** [comment]
I have recently switch Statamic to use a database. I have the same issue when trying to reorder a collection. 
Do you have any update on that issue ? @enespolat24

**Comment by enespolat24** [comment]
Sadly no. still looking for a solution

**Comment by ryanmitchell** [comment]
Can you check this against the new v1? I think this issue can be closed.

**Comment by ryanmitchell** [comment]
I'm able to reproduce and I'm not seeing it re-ordering correctly anywhere, even on the front end. 

We'll need to update EntryQueryBuilder to orderBy the `order` in the tree - so select the tree, get the ids then order by field (but this is MySQL specific).

The other option would be to get all entries then defer to OrderedQueryBuilder... but this means less processing on the database side so its not ideal.

**Comment by enespolat24** [comment]
sorry for the late reply, yes the issue is still present with v1 eloquent-driver

**Comment by ryanmitchell** [comment]
@enespolat24 see if this PR fixes it... https://github.com/statamic/eloquent-driver/pull/57

**Comment by enespolat24** [comment]
sorry for the late reply, still have issues. when i hit the save button it reverts new order as it was before
