### ISSUE TITLE
Support for optional slugs

### ISSUE THREAD

**Issue by fjahn** [statamic/eloquent-driver#46]
Since [Statamic 3.2.27](https://github.com/statamic/cms/releases/tag/v3.2.27), slugs can be optional. However, currently, the database table prohibits entries with missing slugs.

If someone tries to save an entry from a collection that has no slugs, it leads to this exception:

`SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'slug' cannot be null`

**Comment by ryanmitchell** [comment]
Can you check this against v1? I think this issue can be closed.
