### ISSUE TITLE
Issue with missing parameters

### ISSUE THREAD

**Issue by sobotkap10** [statamic/eloquent-driver#47]
![image](https://user-images.githubusercontent.com/81413106/170010321-e1432605-124e-413b-8a8a-3269c20dcd09.png)

![image](https://user-images.githubusercontent.com/81413106/170010474-010781f8-7371-428d-bf1d-615b07249ac8.png)

![image](https://user-images.githubusercontent.com/81413106/170010633-720098ea-bbe0-4195-af04-dab6e83df333.png)

**Comment by ryanmitchell** [comment]
Fixed here: https://github.com/statamic/eloquent-driver/pull/42/commits/8f00e25417da2d4766e22276bfac9027f0a74784

**Comment by ryanmitchell** [comment]
Can you check this against v1? I think this issue can be closed.
