### ISSUE TITLE
Form submission created_at null

### ISSUE THREAD

**Issue by enespolat24** [statamic/eloquent-driver#61]
Hi , when you post a submission , created_at is null. I made this pr to fix it : #60 

<img width="731" alt="image" src="https://user-images.githubusercontent.com/21336979/191555953-ed1aa277-e607-4273-acb0-b3eafe7f3b93.png">

**Comment by Crasheng** [comment]
I have the same issue

**Comment by espenlg** [comment]
We're also having this problem.

**Comment by enespolat24** [comment]
We found solution this and waiting for a merge at #60

**Comment by espenlg** [comment]
> We found solution this and waiting for a merge at #60
Yes, I noticed and applied a patch. Working fine 👍

**Comment by ryanmitchell** [comment]
Can you close this off now that 60 has been merged and released?

**Comment by jasonvarga** [comment]
Oops yeah I had assumed the PR would have linked to this.

**Comment by ryanmitchell** [comment]
Think it has to be in the initial description for that.
