### ISSUE TITLE
Only entries are stored in DB

### ISSUE THREAD

**Issue by webigniters** [statamic/eloquent-driver#62]
After running:

composer require statamic/eloquent-driver
php artisan vendor:publish --tag="statamic-eloquent-config"
And running the steps for a fresh install,

I found that there was only an Entries table in the DB and that in the config also only Entries are specified.

How can I enable the other items as well?

**Comment by ryanmitchell** [comment]
Can you run `php please support:details` and share the output?

**Comment by webigniters** [comment]
-> php please support:details
Statamic 3.3.40 Pro
Laravel 8.83.24
PHP 7.4.13
statamic/eloquent-driver 0.3.0

Why am I on 0.3.0?

**Comment by ryanmitchell** [comment]
Version 1 requires PHP8+, so you would need to update to that

**Comment by webigniters** [comment]
Ah right, thanks...
I will check it out.

**Comment by ryanmitchell** [comment]
@webigniters for reference: https://github.com/statamic/eloquent-driver/blob/2c4a775accb30803120b009209bc80ebcca23093/composer.json#L25

**Comment by webigniters** [comment]
Why is there still only an entries table?

`Publishing complete.
-> php artisan vendor:publish --tag="statamic-eloquent-config"
Copied File [\vendor\statamic\eloquent-driver\config\eloquent-driver.php] To [\config\statamic\eloquent-driver.php]
Publishing complete.
-> php artisan vendor:publish --tag="statamic-eloquent-entries-table"
Copied File [\vendor\statamic\eloquent-driver\database\migrations\create_entries_table.php.stub] To [\database\migrations\2022_10_04_071205_create_entries_table.php]
Publishing complete.
-> php please support:details
Statamic 3.3.40 Pro
Laravel 8.83.24
PHP 8.1.11
statamic/eloquent-driver 1.0.1
-> php artisan vendor:publish --tag="statamic-eloquent-collections-table"
No publishable resources for tag [statamic-eloquent-collections-table].
Publishing complete.
-> php artisan migrate
Migrating: 2022_10_04_071205_create_entries_table
Migrated:  2022_10_04_071205_create_entries_table (75.22ms)
`

The config file now does have the full package of items.
Now when I try to access CP it (obviously) states:
**Base table or view not found**

**Comment by ryanmitchell** [comment]
Did you run `php artisan vendor:publish --provider="Statamic\Eloquent\ServiceProvider" --tag=migrations` ?

**Comment by ryanmitchell** [comment]
Any update on this @webigniters? did you get it resolved?

**Comment by webigniters** [comment]
Yes, I seem to have forgotten the command you specified.
Thanks for the help. It works just like it should now.

I have added my own migrations for this project as well.
bigint fields are somewhat overkill in my project.

**Comment by ryanmitchell** [comment]
Great, can you close the issue?
