### ISSUE TITLE
`lastModified()` not returning correct date

### ISSUE THREAD

**Issue by helloiamlukas** [statamic/eloquent-driver#65]
#### Description
If you try to get the `updated_at` value via the `lastModified()` method, it does not return the correct date.

The problem seems to be that the `$entry->get('updated_at')` method call is already returning a `Carbon` instance. When using the file driver, it returns a string.

This causes `lastModified()` to parse the date again: https://github.com/statamic/cms/blob/3.3/src/Data/TracksLastModified.php#L13

**Comment by ryanmitchell** [comment]
Hmm yeah, probably need to override the `lastModified` function rather than `fileLastModified`. Do you want to work on it?

**Comment by helloiamlukas** [comment]
I opened a PR now :)

**Comment by JuanS** [comment]
PR working great for me, fixes the issue
