### ISSUE TITLE
Postgres: Can't create entry

### ISSUE THREAD

**Issue by helloiamlukas** [statamic/eloquent-driver#67]
#### Description
When using Postgres, the following error will be thrown when trying to create a new entry:
```
SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "id" violates not-null constraint
```

The driver tries to use `null` as value for the `id` column for new entries.
https://github.com/statamic/eloquent-driver/blob/2c4a775accb30803120b009209bc80ebcca23093/src/Entries/Entry.php#L44-L46

Can we just delete this line, so that the `id` will not be written? Or is there any case where we need the `id` to be there?

**Comment by edalzell** [comment]
@ryanmitchell is the fix above the right one?

**Comment by ryanmitchell** [comment]
Yeah I think its fine to drop if from the fill, its picked up by the findOrNew()
