### ISSUE TITLE
Clear Cache Error

### ISSUE THREAD

**Issue by crackAT** [statamic/eloquent-driver#7]
Hi, 

clearing the content Stache cache manually runs into an error: 

ErrorException
Trying to get property 'origin' of non-object
/admin/utilities/cache/cache/stache

Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
vendor/statamic/eloquent-driver/src/Entries/Entry.php:72

**Comment by jasonvarga** [comment]
Please provide the entire stack trace.

**Comment by crackAT** [comment]
Hi, 

cannot reproduce the error anymore :/ i will reopen the issue with the stack trace if the error occurs again.
