### ISSUE TITLE
Imported Navs lose their order

### ISSUE THREAD

**Issue by jackmcdade** [statamic/eloquent-driver#74]
I have a structured collection built out in flat files, but when running the navs importer the tree data is lost.

**Comment by ryanmitchell** [comment]
I would be hopeful that https://github.com/statamic/eloquent-driver/pull/57 fixes that

**Comment by jackmcdade** [comment]
Ahh, so maybe it's only a problem with UUID based IDs?

**Comment by ryanmitchell** [comment]
I think the order of one level deep structures was being lost / not saved properly. That PR fixes it. Maybe not relevant to your data - but I’d happily look into it if I can get access to the repo?

**Comment by ryanmitchell** [comment]
Looks like jason fixed this in 1.0.3 ([this commit](https://github.com/statamic/eloquent-driver/commit/222388aa13e3da5ae6ca388a3355bd41f4adbe02))
