### ISSUE TITLE
Filters should be case insensitive

### ISSUE THREAD

**Issue by edalzell** [statamic/eloquent-driver#8]
Using the Eloquent driver for entries.

When I try to filter the entries, it's taking the search w/ case sensitivity. i.e.. I have an entry w/ title of `Cochon`, but I can't filter on `coch`, only finds it if I do `Coch`.

I am using Postgres, which is case SENSITIVE by default. Additionally we're in JSON land here so that may also be a factor.

**Comment by jasonvarga** [comment]
I don't think this has to do with this package.

If you're actually _filtering_ using filters, then the "contains" option uses a `LIKE` query which on Postgres is case sensitive.
Although I think you can set up your Postgres DB to be case insensitive. I could be wrong there.
Anyway, if you're using a filter, that's part of statamic/cms, and not this package.

If you're performing a search, and you don't have a search index configured, it'll do a LIKE query too. Same story.
If you do have a search index, I don't think case should be an issue. Either way, something for statamic/cms, not here. Thanks!
