### ISSUE TITLE
[Planetscale Compatibility] Add option to skip foreign key constraints 

### ISSUE THREAD

**Issue by jackmcdade** [statamic/eloquent-driver#97]
I'm working on testing Statamic with PlanetScale and ran into this issue here:

```
 SQLSTATE[HY000]: General error: 1105 foreign key constraints are not allowed, see https://vitess.io/blog/2021-06-15-online-ddl-why-no-fk/ (SQL: alter table `form_submissions` add constraint `form_submissions_form_id_foreign` foreign key (`form_id`) references `forms` (`id`) on delete cascade)
 ```

I'm not quite sure what the best way to check for configure excluding [this line](https://github.com/statamic/eloquent-driver/blob/master/database/migrations/create_form_submissions_table.php.stub#L12). 

Thoughts?

**Comment by ryanmitchell** [comment]
Id be happy to drop the foreign key entirely for what it’s worth.

**Comment by jackmcdade** [comment]
Pretty low risk, right? You could always add your own constraint later if you want those cascading deletes.

**Comment by ryanmitchell** [comment]
Yep

**Comment by jackmcdade** [comment]
Then let's burn it with fire! 🔥

**Comment by ryanmitchell** [comment]
Sure :) Here ya go: https://github.com/statamic/eloquent-driver/pull/98

**Comment by ryanmitchell** [comment]
That ones maybe a bit more controversial, but I've updated the PR and Jason can make the call on it :)

**Comment by FrittenKeeZ** [comment]
@jackmcdade if you delete a form, are submissions automatically deleted by Statamic as well?

**Comment by jasonvarga** [comment]
> if you delete a form, are submissions automatically deleted by Statamic as well?

Yes
