### ISSUE TITLE
[PlanetScale Compatibility] All tables need a primary key

### ISSUE THREAD

**Issue by jackmcdade** [statamic/eloquent-driver#99]
The `password_resets` table has no unique key, which prevents you from promoting a DB branch to production.

<img width="752" alt="CleanShot 2022-11-29 at 14 22 50@2x" src="https://user-images.githubusercontent.com/44739/204628216-f8af1c38-7424-4895-aeed-be037ecd8eb8.png">

Any harm in adding a basic primary, auto-incrementing `id` column?

**Comment by jasonvarga** [comment]
`password_resets` is not part of the eloquent driver, it's in statamic/statamic.
There should be no harm in adding it to your own migration though.

fyi that migration is a direct copy from laravel/laravel into statamic/statamic

https://github.com/laravel/laravel/blob/9.x/database/migrations/2014_10_12_100000_create_password_resets_table.php
